version: 0.2
phases:
  build:
    commands:
      - cd ecs
      #az
      #- export BUCKET=codepipeline-us-east-1-lambda-659660391320
      #lab
      - export BUCKET=codepipeline-us-east-1-749760997813
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  files:
    - ecs/template.yml
    - ecs/outputtemplate.yml
