--- 
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Outputs the time"
Resources: 
  EcsScanner: 
    Type: "AWS::Serverless::Function"
    Properties: 
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./
      Events: 
        EBRule: 
          Properties: 
          Type: EventBridgeRule
            EventBusName: default
            Pattern: 
              detail: 
                source: 
                  - aws.ecs
